# Generated by Django 4.2.29 on 2026-03-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=200)),
                ('total_depth_cm', models.FloatField(help_text='Physical depth of the bin in cm')),
                ('threshold_cm', models.FloatField(default=20.0, help_text='Distance threshold (cm) below which bin is considered near-full')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bin_id'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_cm', models.FloatField(help_text='Raw ultrasonic sensor distance in cm')),
                ('fill_percentage', models.FloatField(help_text='Computed fill level (0-100%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='bins.bin')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
